export const MAIN_ROUTE='/'
export const GAMEONE_ROUTE = '/moving/:id'
export const ONESAVE_ROUTE = '/moving/:id/save'
export const GAMETWO_ROUTE = '/improv/:id'
export const GAMETHREE_ROUTE = '/delegation/:id'
export const THREE_ONLYGAME_ROUTE = '/delegation/:id/game'
export const GAMEFOUR_ROUTE = '/truths_lie/:id'
export const FOUR_ONLYGAME_ROUTE = '/truths_lie/:id/game'
